import '../globals.css';
import {Inter} from 'next/font/google';
import styles from './layout.module.css';
import Link from "next/link";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function ProductsLayout({
                                           children,
                                       }: {
    children: React.ReactNode
}) {
    return (
        <>
            <nav className={styles.nav}>
                <Link href='/products/woman'>여성옷</Link>
                <Link href='/products/man'>남성옷</Link>
            </nav>
            <section className={styles.product}>
                {children}
            </section>
        </>
    )
}
